### ISSUE TITLE
雷达图移除样式问题

### ISSUE THREAD

**Issue by wThunder** [williamyuanjw/DM_screen_web#1]
### 操作步骤

1. 点击登录之后无任何操作
2. 项目中间雷达图初始五个,选中雷达图之后remove,连续删除之后如下图
![image](https://github.com/williamyuanjw/DM_screen_web/assets/74393053/42a850b4-a09c-4ae1-a9d2-2b83c213fb13)

**Comment by williamyuanjw** [comment]
我这边复现不了你的问题 这是你本地调试改过之后的代码吗

**Comment by wThunder** [comment]
我在你的预览网站上面看的 这个问题确实不太好复现

**Comment by williamyuanjw** [comment]
现在应该是没这个问题的 可能你有缓存之类的 因为我这边的标题是这样的
![image](https://github.com/williamyuanjw/DM_screen_web/assets/107539476/8214fb57-ac95-491d-9cbf-d605ccad4d7a)
然后你的图片相同地方显示的标题和我的不一样 所以就有可能是别的问题造成的
